module.exports = {
    unknownCommand: "I could not run that command.",
    notInGuild: "This command can only be used in a guild.",
    notAuth: "This command can only be used by an admin.",
    error: "I could not run that command, please contact your server administrator.",
    adminRole: "op",
    unknownRole: "This server is missing the admin role, please contact your server administrator.",
    notSettingUpEnd: "You have not setup the form.",
    setSubmissionsReply: "Form submissions will now be sent to you.",
    setSubmissionsChannelReply: "Form submissions will now be posted in this channel.",
    submissionsNotSet: "Submissions have not been set, please contact your server administrator",
    applicationCancel: "Application canceled.",
    applicationFormFalseCancel: "You have not started an application form yet.",
    applicationSent: "Congratulations, Your Application form has been submitted and will be reviewed within 24h.",
    formSetupInProgress: "Someone else is already configuring the form.",
    newFormSetup: "The new form has been setup.",
    reasonAgeMessage: params => `Hey ${params.user},\n\nThank you for your application to join Create Technical. We appreciate your interest in CT and your time filling out the application. While we are thankful for the time you took and your interest, we sadly have to decline your admission at this time.\n\nUnfortunately our current player base is older and we feel uncomfortable exposing those who are on the younger side to more mature content.\n\nThanks again for taking the time to apply. We wish you the best of luck in your journey with the Create mod.\n\nSincerely,\n\nThe Create Technical Team`,
    reasonBadFitMessage: params => `Hey ${params.user},\n\nThank you for your application to join Create Technical. We appreciate your interest in CT and your time filling out the application. While we are thankful for the time you took and your interest, we sadly have to decline your admission at this time.\n\nWe're looking for members with a little more experience with create as this is more a place for experienced players rather than someone just starting out. We would love to have you apply again down the road when you have spent more time playing with Create!\n\nThanks again for taking the time to apply. We wish you the best of luck in your journey with the Create mod.\n\nSincerely,\n\nThe Create Technical Team`,
    reasonBadAppMessage: params => `Hey ${params.user},\n\nThank you for your application to join Create Technical. We appreciate your interest in CT and your time filling out the application. While we are thankful for the time you took and your interest, we sadly have to decline your admission at this time.\n\nWe’re looking for members who fit our community well. To be able to determine whether this is the case, we ask that your application is clear, concise, and well-written. The reason you are seeing this message is because that was not the case. We ask that you reapply in a while with more information, or if this is your second or third time trying, endeavour to find another community that might better suit you.\n\nThanks again for taking the time to apply. We wish you the best of luck in your journey with the Create mod.\n\nSincerely,\n\nThe Create Technical Team`,
    formReceiveMessage: params => `${params.user} has submitted an Application form and should be reviewed.`,
    formApplyMessage: params => `Application commands: \`\`\`${params.botChar}cancel, ${params.botChar}redo\`\`\``,
    formSetupMessage: params => `Enter questions and enter \`${params.botChar}endsetup\` when done.`
}